### ISSUE TITLE
suggestion for profile setting

### ISSUE THREAD

**Issue by SydOps** [manheim/awssume#3]
I came from ticket https://github.com/hashicorp/terraform/issues/1275,  seems your gem need seperate profile files. I prefer to follow the standard AWS CLI (Command Line Interface) settings to read exist `.aws/credentials` and `.aws/config`.

.aws/config supports profile and defines as below: 
```
[profile stag]
region = us-east-2
source_profile = default
role_arn = arn:aws:iam::xxxx:role/CrossAccount

[profile prod]
region = us-east-1
source_profile = default
role_arn = arn:aws:iam::xxxx:role/CrossAccount
```
Why we need manage two or more aws api key configurations or feed it via command line? Make it simple and no duplication. 

`source_profile` can limit which account to be used. 

So we should have something set as below

    awssume -profile stag <terraform command>

**Comment by reppard** [comment]
@SydOps There would be a little bit of work to support this enhancement request.  I think the most simplistic approach would be to add support for ``AWS_DEFAULT_PROFILE``.

Would something like this work for your use case?

```
AWS_DEFAULT_PROFILE=stage awssume <terraform command>
```

**Comment by SydOps** [comment]
@reppard 

That's better. Accept system environments or feed with options in command.

**Comment by SydOps** [comment]
One more feature is, even run in default account (the source profile), we should support STS to generate temp token (that mean we don't use the default api account directly) , then we have same setting across all platforms/accounts.

In boto/python, it is call `get_session_token`, 

http://boto.cloudhackers.com/en/latest/ref/sts.html#boto.sts.STSConnection.get_session_token

Different with assume role (http://boto.cloudhackers.com/en/latest/ref/sts.html#boto.sts.STSConnection.assume_role)

**Comment by reppard** [comment]
@SydOps I apologies for the lack of movement or feedback on this issue.  After some thinking I don't feel this gem should cover this specific use case.  This gem was written so that EC2 instances with Instance Profiles could assume a role and use the resulting credentials to do some work.  In our case Instance Profiles are preferred over having shared profile/credential files on the EC2 instance.  I'm going to close this issue but please feel free to open other issues or pull requests in the future.  Thank you for your contributions to this thread!
